[workspace]
resolver = "2"
members = ["crates/*", "programs/*"]

[workspace.dependencies]
faucet = { path = "./programs/faucet" }
litesvm = { git = "https://github.com/OliverNChalk/litesvm" }
solana-account-decoder = "1.18"
solana-client = "1.18"
solana-logger = "1.18"
solana-program = "1.18"
solana-sdk = "1.18"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
